### PR TITLE
Nav bar styling

### PR DESCRIPTION
**Pull request by PatrickBrown1**
Styled the nav-bar and created a logo for it. Currently, it just links to the Community Page, Profile page, Search Page, and Log In Page.

### CODE REVIEW

**Review by hexalellogram — APPROVED** [review]
Looks good to me! I'll make sure to have someone else from frontend review this as well before we merge.

**Comment by jettbui** [comment]
Navbar seems to be scrollable on my end, otherwise LGTM!

**Review by hexalellogram — CHANGES_REQUESTED** [review]
Jett is right, navbar is scrollable

**Review by jettbui — APPROVED** [review]
let's get this money!

**Review by hexalellogram — APPROVED** [review]
Looks good to me! @PatrickBrown1 feel free to merge!

**Pull request merged**
