### PR TITLE
Page layout templates

### PR DESCRIPTION
**Pull request by anuragasthana**
I made the basic templates for the components of each page based on the Figma and our discussions. This is pretty high level so if we need to add more components within these later on we can do so. Let me know if you have any questions or if there's anything we want to modify. Thanks!

### CODE REVIEW

**Comment by hexalellogram** [comment]
@anuragasthana Linting is still failing so take a look at the "Details" next to the Travis CI push and pr logs to see what went wrong. Let me know if you have any questions. Most of these are simple stylistic issues that can be quickly fixed.

**Review by PatrickBrown1 — CHANGES_REQUESTED** [review]
Some of these pages already exist (i.e the LogIn page and css). Instead of creating new files for them, try to move the old ones into the correct directory!

**Review by PatrickBrown1 — CHANGES_REQUESTED** [review]
Checked in. I'll move my components into this folder once it's merged. Once you fix linting errors I'll approve!

**Review by PatrickBrown1 — APPROVED** [review]
LGTM!

**Review by hexalellogram — APPROVED** [review]
Looks good to me! @anuragasthana feel free to merge!

**Pull request merged**
