### PR TITLE
User profile page

### PR DESCRIPTION
**Pull request by anguyen698**

### CODE REVIEW

**Review by hexalellogram — CHANGES_REQUESTED** [review]
Remove extraneous s's in `index.html`

**Review by hexalellogram — CHANGES_REQUESTED** [review]
I'm noticing `logo` in `App.js` (line 2) is never used and it's causing linting to fail, please remove that particular import so we can pass the linting.

**Review by hexalellogram — CHANGES_REQUESTED** [review]
Travis is still failing linting (different linting issues this time), so check out https://travis-ci.org/github/acmucsd/acm-profiles-ui/builds/743279460 to see what it's complaining about and fix the issues there (like the semicolons, for example).

**Comment by hexalellogram** [comment]
Still a few linting failures as of rn (Friday 11/13 at 2:35 AM). should be (relatively) easy to solve because most of them are simple stylistic changes. Also there are conflicts in the package files too, so that is something we need to resolve before merging.

**Comment by anguyen698** [comment]
I'm not sure how to resolve the conflicts in the package files yet, but I'll ask a mentor for help! Thanks Bryce!

**Pull request closed without merging**
