### PR TITLE
Better Routing

### PR DESCRIPTION
**Pull request by jettbui**
**Routes:**

- "/": reroutes to login page if not authenticated, reroutes to the authenticated user's profile page otherwise
- "/search": proceeds to search page
- "/login": proceeds to login page if not authenticated, reroutes to the authenticated user's profile page otherwise
- "/user/:id": proceeds to user's page with given id, if there is no :id then it reroutes to search page
- "/community/:id": proceeds to community's page with given id, if there is no :id then it reroutes to search page

**Todo:**
- Authentication is not implemented so it is currently hardcoded to always be authenticated
- Authenticated user ID is 123456 for the same reason above
- ID verification for "/user/:id" and "/community/:id" routes (backend needed), maybe reroute to search page if invalid id?

**Note:**
To access URL params within each page component do the following:
For example, if the URL was `/user/111222333`
```javascript
/* in user-profile-page.js */
import { useParams } from "react-router-dom"
/* ... */
const { id } = useParams()
print(id) // '111222333'
```

I know we haven't agreed on a specific routing scheme so if there's any changes to be made let me know!

### CODE REVIEW

**Review by hexalellogram — APPROVED** [review]
Looks good to me! Just be sure to add an issue for handling authentication if we don't already have one open, as well as the other todos you mentioned.

**Review by PatrickBrown1 — CHANGES_REQUESTED** [review]
We should probably set up a dummy LogIn page later to test this. (i.e. make a button on the log in page that automatically sets authentication to true with userId 123456), I'll do this now.

**Review by PatrickBrown1 — APPROVED** [review]

**Review by PatrickBrown1 — APPROVED** [review]
Looks good

**Review by hexalellogram — APPROVED** [review]
Looks good! Just remember to open the issue for the redirect so we remember to take care of that

**Pull request merged**
