### PR TITLE
Search page development

### PR DESCRIPTION
**Pull request by PatrickBrown1**
Developed search page, including

- Search Bar with a dropdown to change between community search and user search
- A create community modal component, that allows users to create a new community

Still todo:
- Recommendation feature (should be simple once we link with the backend)
- Link search functionality and create community with backend

### CODE REVIEW

**Comment by hexalellogram** [comment]
Is not having the new navbar expected? It's not an issue that'll block merging, there are no file conflicts, I'm just making sure that is not a bug with the deployment or the code.

**Comment by PatrickBrown1** [comment]
> Is not having the new navbar expected? It's not an issue that'll block merging, there are no file conflicts, I'm just making sure that is not a bug with the deployment or the code.

This branch was made before I developed the navbar in a separate branch. The updated navbar is already in the main branch, it should merge properly to include both the search page and navbar (this branch is just behind main by a little).

**Review by jettbui — APPROVED** [review]
looks great!!

**Review by hexalellogram — APPROVED** [review]
Looks good to me, approved!

**Pull request merged**
